server:
  port: 8085

spring:
  application:
    name: function-catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5432/function_catalog_db
    username: postgres
    password: doniyor2007
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: ApeVFjUOyTmk7XYwgcYwIEsix1mALAsQhftYQqWHE8P6kcnqbZv0Uxj9HduKEvjXzz0sVYCG0ZjSBtmxadtAiQ==

springdoc:
  swagger-ui:
    path: /swagger