version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  identity-service:
    build: ./identity-service
    container_name: identity-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/adlita_project1
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      AZURE_TRANSLATOR_ENDPOINT: ${AZURE_TRANSLATOR_ENDPOINT}
      AZURE_TRANSLATOR_KEY: ${AZURE_TRANSLATOR_KEY}
      AZURE_TRANSLATOR_REGION: ${AZURE_TRANSLATOR_REGION}
      FUNCTION_CATALOG_SERVICE_BASE_URL: http://function-catalog-service:8085
      REFERENCE_SERVICE_BASE_URL: http://reference-service:8084
    depends_on:
      - postgres
      - eureka-server

  reference-service:
    build: ./reference-service
    container_name: reference-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/reference_service_db
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      AZURE_TRANSLATOR_ENDPOINT: ${AZURE_TRANSLATOR_ENDPOINT}
      AZURE_TRANSLATOR_KEY: ${AZURE_TRANSLATOR_KEY}
      AZURE_TRANSLATOR_REGION: ${AZURE_TRANSLATOR_REGION}
    depends_on:
      - postgres
      - eureka-server

  function-catalog-service:
    build: ./function-catalog-service
    container_name: function-catalog-service
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/function_catalog_db
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      AZURE_TRANSLATOR_ENDPOINT: ${AZURE_TRANSLATOR_ENDPOINT}
      AZURE_TRANSLATOR_KEY: ${AZURE_TRANSLATOR_KEY}
      AZURE_TRANSLATOR_REGION: ${AZURE_TRANSLATOR_REGION}
      IDENTITY_SERVICE_BASE_URL: http://identity-service:8081
    depends_on:
      - postgres
      - eureka-server

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8082:8082"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
      - identity-service
      - reference-service
      - function-catalog-service

volumes:
  pgdata:
