server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - http://localhost:3000
                  - http://localhost:5173
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
          routes:
            - id: identity-language-service
              uri: lb://identity-service
              predicates:
                - Path=/api/languages,/api/languages/**
            - id: reference-service
              uri: lb://reference-service
              predicates:
                - Path=/api/regions/**,/api/interface-translations/**
            - id: function-catalog-service
              uri: lb://function-catalog-service
              predicates:
                - Path=/api/functions/**
            - id: identity-service
              uri: lb://identity-service
              predicates:
                - Path=/api/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
