server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: reference-service
              uri: lb://reference-service
              predicates:
                - Path=/api/regions/**,/api/languages/**
            - id: function-catalog-service
              uri: lb://function-catalog-service
              predicates:
                - Path=/api/functions/**
            - id: identity-service
              uri: lb://identity-service
              predicates:
                - Path=/api/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true