server:
  port: 8084

spring:
  application:
    name: reference-service
  config:
    import: optional:file:.env[.properties],optional:file:../.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/reference_service_db
    username: postgres
    password: doniyor2007
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: ApeVFjUOyTmk7XYwgcYwIEsix1mALAsQhftYQqWHE8P6kcnqbZv0Uxj9HduKEvjXzz0sVYCG0ZjSBtmxadtAiQ==

springdoc:
  swagger-ui:
    path: /swagger

azure:
  translator:
    endpoint: ${AZURE_TRANSLATOR_ENDPOINT:https://api.cognitive.microsofttranslator.com}
    key: ${AZURE_TRANSLATOR_KEY:}
    region: ${AZURE_TRANSLATOR_REGION:}
