server:
  port: 8084

spring:
  application:
    name: reference-service
  datasource:
    url: jdbc:postgresql://localhost:5432/reference_service_db
    username: postgres
    password: 12022005
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true