server:
  port: 8084

spring:
  application:
    name: reference-service
  config:
    import: optional:file:.env[.properties],optional:file:../.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/reference_service_db
    username: postgres
    password: ${REFERENCE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  cache:
    type: caffeine

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    path: /swagger
