CREATE TABLE IF NOT EXISTS translation_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    translation_key VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    required BOOLEAN NOT NULL DEFAULT TRUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_translation_keys_translation_key UNIQUE (translation_key)
);

CREATE TABLE IF NOT EXISTS translations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    translation_key_id BIGINT NOT NULL,
    language_code VARCHAR(64) NOT NULL,
    translation_value TEXT NOT NULL,
    CONSTRAINT fk_translations_translation_key
        FOREIGN KEY (translation_key_id) REFERENCES translation_keys (id),
    CONSTRAINT uk_translations_language_key
        UNIQUE (language_code, translation_key_id)
);

CREATE INDEX IF NOT EXISTS idx_translations_language_code
    ON translations (language_code);

DO $migration$
BEGIN
    IF to_regclass('public.interface_translations') IS NOT NULL THEN
        EXECUTE $sql$
            INSERT INTO translation_keys (translation_key, required, active)
            SELECT DISTINCT translation_key, TRUE, TRUE
            FROM interface_translations
            ON CONFLICT (translation_key) DO NOTHING
        $sql$;

        EXECUTE $sql$
            INSERT INTO translations (translation_key_id, language_code, translation_value)
            SELECT translation_keys.id,
                   interface_translations.language_code,
                   interface_translations.translation_value
            FROM interface_translations
            JOIN translation_keys
              ON translation_keys.translation_key = interface_translations.translation_key
            ON CONFLICT (language_code, translation_key_id) DO NOTHING
        $sql$;
    END IF;
END;
$migration$;

CREATE TEMPORARY TABLE interface_translation_seed (
    translation_key VARCHAR(150) PRIMARY KEY,
    translation_value TEXT NOT NULL
);

INSERT INTO interface_translation_seed (translation_key, translation_value) VALUES
('app.name', 'Reestr Task'),
('app.tagline', 'State services catalogue — demo project'),
('app.demoNotice', 'This is not an official government portal — a demo product.'),
('nav.home', 'Home'),
('nav.organizations', 'Organizations'),
('nav.functions', 'Services'),
('nav.admin', 'Admin panel'),
('nav.security', 'Security'),
('nav.dashboard', 'Dashboard'),
('nav.orgAdmins', 'Org admins'),
('nav.moderators', 'Moderators'),
('nav.roles', 'Roles & permissions'),
('nav.languages', 'Languages'),
('nav.legacyUsers', 'Users'),
('nav.catalog', 'Catalogue'),
('nav.backToSite', 'Back to site'),
('action.login', 'Sign in'),
('action.logout', 'Sign out'),
('action.save', 'Save'),
('action.cancel', 'Cancel'),
('action.create', 'Create'),
('action.edit', 'Edit'),
('action.delete', 'Delete'),
('action.deactivate', 'Deactivate'),
('action.confirm', 'Confirm'),
('action.close', 'Close'),
('action.back', 'Back'),
('action.retry', 'Try again'),
('action.search', 'Search'),
('action.reset', 'Reset'),
('action.viewAll', 'View all'),
('action.details', 'Details'),
('action.promote', 'Promote'),
('action.add', 'Add'),
('action.assign', 'Assign'),
('field.id', 'ID'),
('field.name', 'Name'),
('field.fullName', 'Full name'),
('field.firstName', 'First name'),
('field.lastName', 'Last name'),
('field.description', 'Description'),
('field.email', 'Email'),
('field.password', 'Password'),
('field.phone', 'Phone'),
('field.role', 'Role'),
('field.status', 'Status'),
('field.enabled', 'Enabled'),
('field.createdAt', 'Created'),
('field.organization', 'Organization'),
('field.organizations', 'Organizations'),
('field.organizationIds', 'Organization IDs'),
('field.category', 'Category'),
('field.requirements', 'Requirements'),
('field.region', 'Region'),
('field.language', 'Language'),
('field.actions', 'Actions'),
('field.optional', 'optional'),
('status.active', 'Active'),
('status.inactive', 'Inactive'),
('status.all', 'All'),
('state.loading', 'Loading…'),
('state.emptyTitle', 'Nothing found'),
('state.emptyText', 'Try changing the filters or clearing the search.'),
('state.errorTitle', 'Something went wrong'),
('state.notFoundTitle', 'Page not found'),
('state.notFoundText', 'The data you requested was removed or the address is wrong.'),
('state.forbidden', 'You do not have permission for this action'),
('home.heroBadge', 'State services registry'),
('home.heroTitle', 'Government bodies and their services in one catalogue'),
('home.heroSubtitle', 'Quickly find organizations, functions and required documents.'),
('home.heroSearchPlaceholder', 'Enter a service or organization name…'),
('home.statsOrganizations', 'Active organizations'),
('home.statsFunctions', 'Public services'),
('home.statsRegions', 'Regions'),
('home.catalogTitle', 'Service catalogue'),
('home.catalogSubtitle', 'Filter by organization or category.'),
('home.orgsTitle', 'Active organizations'),
('home.orgsSubtitle', 'Government bodies included in the registry.'),
('home.ctaTitle', 'Admin panel for staff'),
('home.ctaText', 'Manage organizations, staff, roles and service requirements in one place.'),
('home.resultsCount', 'results'),
('org.functionsTitle', 'Organization services'),
('org.emptyFunctions', 'No services have been added for this organization yet.'),
('fn.aboutTitle', 'About the service'),
('fn.requirementsEmpty', 'The list of required documents is not filled in yet.'),
('login.title', 'Sign in'),
('login.subtitle', 'Staff administration panel.'),
('login.invalid', 'Invalid email or password'),
('login.demoHint', 'Demo accounts'),
('login.success', 'Signed in successfully'),
('admin.welcome', 'Welcome'),
('admin.summaryOrgs', 'Organizations'),
('admin.summaryOrgAdmins', 'Org admins'),
('admin.summaryModerators', 'Moderators'),
('admin.summaryFunctions', 'Services'),
('admin.recentOrgs', 'Recent organizations'),
('admin.recentFunctions', 'Service list'),
('orgs.title', 'Organization management'),
('orgs.create', 'Create organization'),
('orgs.edit', 'Edit organization'),
('orgs.deactivateConfirm', 'Deactivate this organization? It will be hidden from the public catalogue.'),
('staff.orgAdminsTitle', 'Org admin management'),
('staff.moderatorsTitle', 'Moderator management'),
('staff.createOrgAdmin', 'New org admin'),
('staff.createModerator', 'New moderator'),
('staff.promoteTitle', 'Promote existing user'),
('staff.selectUser', 'Select a user'),
('staff.deactivateConfirm', 'Deactivate this user?'),
('staff.orgsMandatory', 'The organization list is mandatory — it fully replaces the current one.'),
('roles.title', 'Roles & permissions'),
('roles.createRole', 'Create role'),
('roles.permissions', 'Permissions'),
('roles.editPermissions', 'Edit permissions'),
('roles.assignTitle', 'Assign role to user'),
('roles.deleteConfirm', 'Delete this role?'),
('roles.permissionsPanel', 'Permissions list'),
('lang.title', 'Language settings'),
('lang.current', 'Interface languages'),
('lang.searchTitle', 'ISO language catalogue'),
('lang.searchPlaceholder', 'Language name or code…'),
('lang.addSelected', 'Add selected language'),
('lang.default', 'Default language'),
('lang.deleteConfirm', 'Delete this language?'),
('fnEdit.title', 'Edit service requirements'),
('fnEdit.hint', 'Write each document on a new line.'),
('legacy.title', 'Users (Legacy API)'),
('legacy.badge', 'Legacy API'),
('legacy.notice', 'This section uses the legacy /api/user endpoints. Passwords are never displayed.'),
('legacy.updateNotice', 'Editing only changes first name, last name and email.'),
('legacy.deleteConfirm', 'Delete this user?'),
('security.title', 'Security settings'),
('security.changePassword', 'Change password'),
('security.currentPassword', 'Current password'),
('security.newPassword', 'New password'),
('security.repeatPassword', 'Repeat new password'),
('security.passwordRule', 'Password must be 8–100 characters.'),
('security.mismatch', 'Passwords do not match'),
('security.success', 'Password changed successfully'),
('validation.required', 'This field is required'),
('validation.email', 'Invalid email format'),
('validation.minPassword', 'At least 8 characters'),
('validation.selectOrg', 'Select an organization'),
('toast.created', 'Created successfully'),
('toast.updated', 'Saved successfully'),
('toast.deleted', 'Deleted successfully'),
('toast.deactivated', 'Deactivated');

INSERT INTO translation_keys (translation_key, required, active)
SELECT translation_key, TRUE, TRUE
FROM interface_translation_seed
ON CONFLICT (translation_key) DO NOTHING;

INSERT INTO translations (translation_key_id, language_code, translation_value)
SELECT translation_keys.id, 'en', interface_translation_seed.translation_value
FROM interface_translation_seed
JOIN translation_keys
  ON translation_keys.translation_key = interface_translation_seed.translation_key
ON CONFLICT (language_code, translation_key_id) DO NOTHING;
